# type_effectiveness_matrix.py

from constants.type_constants import *


# Type effectiveness matrix
# Format: (attacking_type, defending_type): multiplier
type_effectiveness = {
    # Normal type
    (NORMAL, ROCK): 0.5,
    (NORMAL, GHOST): 0,
    # Fighting type
    (FIGHTING, NORMAL): 2,
    (FIGHTING, FLYING): 0.5,
    (FIGHTING, POISON): 0.5,
    (FIGHTING, ROCK): 2,
    (FIGHTING, BUG): 0.5,
    (FIGHTING, GHOST): 0,
    (FIGHTING, PSYCHIC): 0.5,
    (FIGHTING, ICE): 2,
    # Flying type
    (FLYING, FIGHTING): 2,
    (FLYING, ROCK): 0.5,
    (FLYING, BUG): 2,
    (FLYING, GRASS): 2,
    (FLYING, ELECTRIC): 0.5,
    # Poison type
    (POISON, POISON): 0.5,
    (POISON, GROUND): 0.5,
    (POISON, ROCK): 0.5,
    (POISON, GHOST): 0.5,
    (POISON, GRASS): 2,
    # Ground type
    (GROUND, FLYING): 0,
    (GROUND, POISON): 2,
    (GROUND, ROCK): 2,
    (GROUND, BUG): 0.5,
    (GROUND, FIRE): 2,
    (GROUND, GRASS): 0.5,
    (GROUND, ELECTRIC): 2,
    # Rock type
    (ROCK, FIGHTING): 0.5,
    (ROCK, FLYING): 2,
    (ROCK, GROUND): 0.5,
    (ROCK, BUG): 2,
    (ROCK, FIRE): 2,
    (ROCK, ICE): 2,
    # Bug type
    (BUG, FIGHTING): 0.5,
    (BUG, FLYING): 0.5,
    (BUG, POISON): 0.5,
    (BUG, GHOST): 0.5,
    (BUG, FIRE): 0.5,
    (BUG, GRASS): 2,
    (BUG, PSYCHIC): 2,
    # Ghost type
    (GHOST, NORMAL): 0,
    (GHOST, GHOST): 2,
    (GHOST, PSYCHIC): 2,
    # Fire type
    (FIRE, ROCK): 0.5,
    (FIRE, BUG): 2,
    (FIRE, FIRE): 0.5,
    (FIRE, WATER): 0.5,
    (FIRE, GRASS): 2,
    (FIRE, ICE): 2,
    (FIRE, DRAGON): 0.5,
    # Water type
    (WATER, GROUND): 2,
    (WATER, ROCK): 2,
    (WATER, FIRE): 2,
    (WATER, WATER): 0.5,
    (WATER, GRASS): 0.5,
    (WATER, DRAGON): 0.5,
    # Grass type
    (GRASS, FLYING): 0.5,
    (GRASS, POISON): 0.5,
    (GRASS, GROUND): 2,
    (GRASS, ROCK): 2,
    (GRASS, BUG): 0.5,
    (GRASS, FIRE): 0.5,
    (GRASS, WATER): 2,
    (GRASS, GRASS): 0.5,
    (GRASS, DRAGON): 0.5,
    # Electric type
    (ELECTRIC, FLYING): 2,
    (ELECTRIC, GROUND): 0,
    (ELECTRIC, WATER): 2,
    (ELECTRIC, GRASS): 0.5,
    (ELECTRIC, ELECTRIC): 0.5,
    (ELECTRIC, DRAGON): 0.5,
    # Psychic type
    (PSYCHIC, FIGHTING): 2,
    (PSYCHIC, POISON): 2,
    (PSYCHIC, PSYCHIC): 0.5,
    # Ice type
    (ICE, FLYING): 2,
    (ICE, GROUND): 2,
    (ICE, FIRE): 0.5,
    (ICE, WATER): 0.5,
    (ICE, GRASS): 2,
    (ICE, ICE): 0.5,
    (ICE, DRAGON): 2,
    # Dragon type
    (DRAGON, DRAGON): 2,
}
